# Generated by Django 6.0.5 on 2026-06-04 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='literature',
            name='indexing_progress',
            field=models.FloatField(default=0.0),
        ),
    ]
