# Generated by Django 6.0.5 on 2026-06-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0002_literature_indexing_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='highlighted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
