# Generated by Django 6.0.5 on 2026-06-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0003_annotation_highlighted_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='rects',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
