# Generated by Django 5.2.15 on 2026-06-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literature', '0004_annotation_rects'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='user_id',
            field=models.CharField(db_index=True, default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='literature',
            name='user_id',
            field=models.CharField(db_index=True, default='default', max_length=255),
        ),
    ]
