"""initial_schema

Revision ID: 274eb64c47ee
Revises: 
Create Date: 2026-04-12 05:33:53.434261+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '274eb64c47ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('columns_json', sa.Text(), nullable=True),
    sa.Column('table_name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('table_name')
    )
    op.create_index(op.f('ix_datasets_id'), 'datasets', ['id'], unique=False)
    op.create_index(op.f('ix_datasets_name'), 'datasets', ['name'], unique=False)
    op.create_table('literature',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('processing_status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'INDEXED', 'FAILED', name='processingstatus'), nullable=False),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_literature_filename'), 'literature', ['filename'], unique=False)
    op.create_index(op.f('ix_literature_id'), 'literature', ['id'], unique=False)
    op.create_index(op.f('ix_literature_processing_status'), 'literature', ['processing_status'], unique=False)
    op.create_table('document_suggestions',
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('authors', sa.Text(), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('publication_venue', sa.String(length=300), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('doi', sa.String(length=100), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('search_query', sa.Text(), nullable=True),
    sa.Column('is_relevant', sa.Boolean(), nullable=True),
    sa.Column('is_imported', sa.Boolean(), nullable=True),
    sa.Column('is_dismissed', sa.Boolean(), nullable=True),
    sa.Column('citation_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_suggestions_dataset_id'), 'document_suggestions', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_document_suggestions_id'), 'document_suggestions', ['id'], unique=False)
    op.create_table('query_history',
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('sql_query', sa.Text(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_history_dataset_id'), 'query_history', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_query_history_id'), 'query_history', ['id'], unique=False)
    op.create_table('notes',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tags', sa.String(length=512), nullable=True),
    sa.Column('dataset_id', sa.Integer(), nullable=True),
    sa.Column('literature_id', sa.Integer(), nullable=True),
    sa.Column('query_id', sa.Integer(), nullable=True),
    sa.Column('linked_note_ids', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.ForeignKeyConstraint(['literature_id'], ['literature.id'], ),
    sa.ForeignKeyConstraint(['query_id'], ['query_history.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_dataset_id'), 'notes', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.create_index(op.f('ix_notes_literature_id'), 'notes', ['literature_id'], unique=False)
    op.create_index(op.f('ix_notes_query_id'), 'notes', ['query_id'], unique=False)
    op.create_table('annotations',
    sa.Column('literature_id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('annotation_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('highlighted_text', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('x_position', sa.Float(), nullable=True),
    sa.Column('y_position', sa.Float(), nullable=True),
    sa.Column('width', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['literature_id'], ['literature.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotations_id'), 'annotations', ['id'], unique=False)
    op.create_index(op.f('ix_annotations_literature_id'), 'annotations', ['literature_id'], unique=False)
    op.create_index(op.f('ix_annotations_note_id'), 'annotations', ['note_id'], unique=False)
    op.create_table('note_relationships',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.Enum('NOTE', 'QUERY', 'DATASET', 'LITERATURE', 'VISUALIZATION', name='entitytype'), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.Enum('REFERENCES', 'DERIVED_FROM', 'RELATED_TO', 'CONTRADICTS', 'SUPPORTS', 'QUESTIONS', name='relationshiptype'), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_relationships_id'), 'note_relationships', ['id'], unique=False)
    op.create_index(op.f('ix_note_relationships_note_id'), 'note_relationships', ['note_id'], unique=False)
    op.create_index(op.f('ix_note_relationships_target_id'), 'note_relationships', ['target_id'], unique=False)
    op.create_index(op.f('ix_note_relationships_target_type'), 'note_relationships', ['target_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_relationships_target_type'), table_name='note_relationships')
    op.drop_index(op.f('ix_note_relationships_target_id'), table_name='note_relationships')
    op.drop_index(op.f('ix_note_relationships_note_id'), table_name='note_relationships')
    op.drop_index(op.f('ix_note_relationships_id'), table_name='note_relationships')
    op.drop_table('note_relationships')
    op.drop_index(op.f('ix_annotations_note_id'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_literature_id'), table_name='annotations')
    op.drop_index(op.f('ix_annotations_id'), table_name='annotations')
    op.drop_table('annotations')
    op.drop_index(op.f('ix_notes_query_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_literature_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_dataset_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_query_history_id'), table_name='query_history')
    op.drop_index(op.f('ix_query_history_dataset_id'), table_name='query_history')
    op.drop_table('query_history')
    op.drop_index(op.f('ix_document_suggestions_id'), table_name='document_suggestions')
    op.drop_index(op.f('ix_document_suggestions_dataset_id'), table_name='document_suggestions')
    op.drop_table('document_suggestions')
    op.drop_index(op.f('ix_literature_processing_status'), table_name='literature')
    op.drop_index(op.f('ix_literature_id'), table_name='literature')
    op.drop_index(op.f('ix_literature_filename'), table_name='literature')
    op.drop_table('literature')
    op.drop_index(op.f('ix_datasets_name'), table_name='datasets')
    op.drop_index(op.f('ix_datasets_id'), table_name='datasets')
    op.drop_table('datasets')
    # ### end Alembic commands ###
