# Generated by Django 6.0.5 on 2026-06-02 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rag", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=500)),
                ("authors", models.TextField(blank=True, null=True)),
                ("publication_year", models.IntegerField(blank=True, null=True)),
                (
                    "publication_venue",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("abstract", models.TextField(blank=True, null=True)),
                ("snippet", models.TextField(blank=True, null=True)),
                ("url", models.CharField(blank=True, max_length=500, null=True)),
                ("pdf_url", models.CharField(blank=True, max_length=500, null=True)),
                ("doi", models.CharField(blank=True, max_length=100, null=True)),
                ("relevance_score", models.FloatField(blank=True, null=True)),
                ("search_query", models.TextField(blank=True, null=True)),
                ("is_relevant", models.BooleanField(blank=True, null=True)),
                ("is_imported", models.BooleanField(default=False)),
                ("is_dismissed", models.BooleanField(default=False)),
                ("citation_count", models.IntegerField(blank=True, null=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="suggestions",
                        to="rag.dataset",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="QueryHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("query_text", models.TextField()),
                ("sql_query", models.TextField(blank=True, null=True)),
                ("result_count", models.IntegerField(blank=True, null=True)),
                ("execution_time_ms", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="queries",
                        to="rag.dataset",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
