# Generated by Django 5.2.15 on 2026-06-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0003_alter_documentsuggestion_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsuggestion',
            name='user_id',
            field=models.CharField(db_index=True, default='default', max_length=255),
        ),
        migrations.AddField(
            model_name='queryhistory',
            name='user_id',
            field=models.CharField(db_index=True, default='default', max_length=255),
        ),
    ]
